
include(ExternalProject)

IF(WIN32 OR MSVC AND PD_BUILD_ASIO)

    SET(ASIOSDK_VERSION 2.3.2)

    ExternalProject_Add(asio_ext
        URL http://www.steinberg.net/sdk_downloads/ASIOSDK${ASIOSDK_VERSION}.zip
        URL_HASH "SHA256=f8380b96cd64929986857466ef530572fabf755ba16a0693a37e4331a02fb692"
        PATCH_COMMAND cmake -E copy
            ${CMAKE_SOURCE_DIR}/cmake/asio/CMakeLists.txt
            ${CMAKE_SOURCE_DIR}/asio/ASIOSDK/CMakeLists.txt
        UPDATE_COMMAND ""
        SOURCE_DIR ${CMAKE_SOURCE_DIR}/asio/ASIOSDK
        BUILD_IN_SOURCE 0
        CONFIGURE_COMMAND ""
        BUILD_COMMAND ""
        INSTALL_COMMAND ""
    )

    MESSAGE(STATUS "ASIO Installing to: ${CMAKE_INSTALL_PREFIX}")
    SET(ASIO_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
    SET(ASIO_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/lib)

    IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        SET(ASIO_LIBRARY "asiod.lib")
    ELSE()
        SET(ASIO_LIBRARY "asio.lib")
    endif()

ENDIF()

IF(PD_BUILD_PORTAUDIO)
    IF(NOT ANDROID)
        ExternalProject_Add(portaudio_ext
            GIT_REPOSITORY https://git.assembla.com/portaudio.git
            GIT_TAG master
            GIT_SHALLOW 1
            UPDATE_COMMAND ""
            BUILD_IN_SOURCE 0
            CMAKE_ARGS
            -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
            -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
            -DPA_ENABLE_DEBUG_OUTPUT=OFF
            -DPA_BUILD_EXAMPLES=OFF
            -DPA_BUILD_TESTS=OFF
            -DPA_DISABLE_INSTALL=OFF
        )
    ELSE()
        ExternalProject_Add(portaudio_ext
            GIT_REPOSITORY https://github.com/Gundersanne/portaudio_opensles.git
            GIT_TAG master
            GIT_SHALLOW 1
            UPDATE_COMMAND ""
            BUILD_IN_SOURCE 0
            CMAKE_ARGS
            -DANDROID_PLATFORM=${ANDROID_PLATFORM}
            -DANDROID_ABI=${ANDROID_ABI}
            -DANDROID_STL=${ANDROID_STL}
            -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
            -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
            -DPA_ENABLE_DEBUG_OUTPUT=OFF
            -DPA_BUILD_EXAMPLES=OFF
            -DPA_BUILD_TESTS=OFF
            -DPA_DISABLE_INSTALL=OFF
        )
    ENDIF()

    MESSAGE(STATUS "PortAudio Installing to: ${CMAKE_INSTALL_PREFIX}")
    SET(PORTAUDIO_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
    SET(PORTAUDIO_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/lib)

    IF(MSVC)
        IF(${TARGET_ARCH} STREQUAL "x86_64")
            SET(LIB_PORTAUDIO portaudio_x64)
        ELSE()
            SET(LIB_PORTAUDIO portaudio_${TARGET_ARCH})
        ENDIF()
    ELSE()
        SET(LIB_PORTAUDIO portaudio)
    ENDIF()

    IF(WIN32 OR MSVC AND PD_BUILD_ASIO)
        add_dependencies(portaudio_ext asio_ext)
    ENDIF()

ENDIF()


IF(PD_BUILD_FFTW3)

    SET(FFTW_VERSION 3.3.8)

    ExternalProject_Add(fftw3_ext
        URL http://www.fftw.org/fftw-${FFTW_VERSION}.tar.gz
        URL_HASH "SHA256=6113262f6e92c5bd474f2875fa1b01054c4ad5040f6b0da7c03c98821d9ae303"
        UPDATE_COMMAND ""
        BUILD_IN_SOURCE 0
        CMAKE_ARGS
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DANDROID_ABI=${ANDROID_ABI}
        -DANDROID_STL=${ANDROID_STL}
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
        -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
        -DBUILD_TESTS=OFF
        -DENABLE_OPENMP=OFF
        -DENABLE_THREADS=ON
        -DWITH_COMBINED_THREADS=OFF
        -DENABLE_FLOAT=OFF
        -DENABLE_LONG_DOUBLE=OFF
        -DENABLE_QUAD_PRECISION=OFF
        -DENABLE_SSE=OFF
        -DENABLE_SSE2=OFF
        -DENABLE_AVX=OFF
        -DENABLE_AVX2=OFF
        -DDISABLE_FORTRAN=ON
        )

    MESSAGE(STATUS "FFTW3 Installing to: ${CMAKE_INSTALL_PREFIX}")
    SET(FFTW_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
    SET(FFTW_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/lib)

    IF(WIN32)
        IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
            SET(FFTW_LIBRARY fftw3d.lib)
        ELSE()
            SET(FFTW_LIBRARY fftw3.lib)
        ENDIF()
    ELSE()
        SET(FFTW_LIBRARY fftw3)
    ENDIF()

ENDIF()

IF(PD_BUILD_PORTMIDI)
    ExternalProject_Add(portmidi_ext
    GIT_REPOSITORY https://github.com/jwinarske/portmidi.git
    GIT_TAG master
    GIT_SHALLOW 1
    UPDATE_COMMAND ""
    BUILD_IN_SOURCE 0
    CMAKE_ARGS
    -DANDROID_PLATFORM=${ANDROID_PLATFORM}
    -DANDROID_ABI=${ANDROID_ABI}
    -DANDROID_STL=${ANDROID_STL}
    -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_VERBOSE_MAKEFILE=${CMAKE_VERBOSE_MAKEFILE}
    )

    MESSAGE(STATUS "PortMidi Installing to: ${CMAKE_INSTALL_PREFIX}")
    SET(PORTMIDI_INCLUDE_DIR ${CMAKE_INSTALL_PREFIX}/include)
    SET(PORTMIDI_LIBRARY_DIR ${CMAKE_INSTALL_PREFIX}/lib)

    IF(WIN32)
        IF("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
            SET(PORTMIDI_LIBRARY portmidid.lib)
        ELSE()
            SET(PORTMIDI_LIBRARY portmidi.lib)
        ENDIF()
    ELSE()
        SET(PORTMIDI_LIBRARY portmidi)
    ENDIF()

ENDIF()