
set(_M_PD_HEADER "src/m_pd.h")


file(STRINGS ${_M_PD_HEADER} out LIMIT_COUNT 1 REGEX "^#define PD_MAJOR_VERSION ")
string(REPLACE "#define PD_MAJOR_VERSION " "" PD_MAJOR_VERSION ${out})

file(STRINGS ${_M_PD_HEADER} out LIMIT_COUNT 1 REGEX "^#define PD_MINOR_VERSION ")
string(REPLACE "#define PD_MINOR_VERSION " "" PD_MINOR_VERSION ${out})

file(STRINGS ${_M_PD_HEADER} out LIMIT_COUNT 1 REGEX "^#define PD_BUGFIX_VERSION ")
string(REPLACE "#define PD_BUGFIX_VERSION " "" PD_BUGFIX_VERSION ${out})

file(STRINGS ${_M_PD_HEADER} out LIMIT_COUNT 1 REGEX "^#define PD_TEST_VERSION ")
string(REPLACE "#define PD_TEST_VERSION " "" PD_TEST_VERSION ${out})


if(BUILD_NUMBER)
    set(PD_VERSION ${PD_MAJOR_VERSION}.${PD_MINOR_VERSION}.${PD_BUGFIX_VERSION}.${BUILD_NUMBER})
else()
    set(PD_VERSION ${PD_MAJOR_VERSION}.${PD_MINOR_VERSION}.${PD_BUGFIX_VERSION}.0)
endif()
